# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: puller.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='puller.proto',
  package='dejavu.puller',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cpuller.proto\x12\rdejavu.puller\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"Y\n\tImagePull\x12\x0c\n\x04repo\x18\x01 \x01(\t\x12\x0b\n\x03tag\x18\x02 \x01(\t\x12\x0e\n\x06\x63lient\x18\x03 \x01(\t\x12\x10\n\x08registry\x18\x04 \x01(\t\x12\x0f\n\x07\x61liases\x18\x05 \x03(\t\"\x9e\x02\n\tLayerStat\x12\x0e\n\x06\x64igest\x18\x01 \x01(\t\x12\x11\n\tfull_size\x18\x02 \x01(\x04\x12\x14\n\x0c\x63ompact_size\x18\x03 \x01(\x04\x12\x0e\n\x06\x65xists\x18\x04 \x01(\x08\x12\x32\n\x0e\x64ownload_start\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0c\x64ownload_end\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rextract_start\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0b\x65xtract_end\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xc2\x01\n\x10ImagePullSummary\x12&\n\x04pull\x18\x01 \x01(\x0b\x32\x18.dejavu.puller.ImagePull\x12.\n\nstart_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12(\n\x06layers\x18\x04 \x03(\x0b\x32\x18.dejavu.puller.LayerStat\"E\n\x06\x43onfig\x12\x10\n\x08\x63\x61pacity\x18\x01 \x01(\x04\x12\x14\n\x0c\x63\x61\x63he_policy\x18\x02 \x01(\t\x12\x13\n\x0buse_archive\x18\x03 \x01(\x08\x32\xcf\x01\n\x0bImagePuller\x12<\n\tSetConfig\x12\x15.dejavu.puller.Config\x1a\x16.google.protobuf.Empty\"\x00\x12G\n\x04Pull\x12\x18.dejavu.puller.ImagePull\x1a\x1f.dejavu.puller.ImagePullSummary\"\x00(\x01\x30\x01\x12\x39\n\x05Prune\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_IMAGEPULL = _descriptor.Descriptor(
  name='ImagePull',
  full_name='dejavu.puller.ImagePull',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='repo', full_name='dejavu.puller.ImagePull.repo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='dejavu.puller.ImagePull.tag', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client', full_name='dejavu.puller.ImagePull.client', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='registry', full_name='dejavu.puller.ImagePull.registry', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aliases', full_name='dejavu.puller.ImagePull.aliases', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=182,
)


_LAYERSTAT = _descriptor.Descriptor(
  name='LayerStat',
  full_name='dejavu.puller.LayerStat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='digest', full_name='dejavu.puller.LayerStat.digest', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='full_size', full_name='dejavu.puller.LayerStat.full_size', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compact_size', full_name='dejavu.puller.LayerStat.compact_size', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exists', full_name='dejavu.puller.LayerStat.exists', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='download_start', full_name='dejavu.puller.LayerStat.download_start', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='download_end', full_name='dejavu.puller.LayerStat.download_end', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extract_start', full_name='dejavu.puller.LayerStat.extract_start', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extract_end', full_name='dejavu.puller.LayerStat.extract_end', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=471,
)


_IMAGEPULLSUMMARY = _descriptor.Descriptor(
  name='ImagePullSummary',
  full_name='dejavu.puller.ImagePullSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pull', full_name='dejavu.puller.ImagePullSummary.pull', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='dejavu.puller.ImagePullSummary.start_time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='dejavu.puller.ImagePullSummary.end_time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layers', full_name='dejavu.puller.ImagePullSummary.layers', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=474,
  serialized_end=668,
)


_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='dejavu.puller.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='capacity', full_name='dejavu.puller.Config.capacity', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cache_policy', full_name='dejavu.puller.Config.cache_policy', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_archive', full_name='dejavu.puller.Config.use_archive', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=670,
  serialized_end=739,
)

_LAYERSTAT.fields_by_name['download_start'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_LAYERSTAT.fields_by_name['download_end'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_LAYERSTAT.fields_by_name['extract_start'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_LAYERSTAT.fields_by_name['extract_end'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_IMAGEPULLSUMMARY.fields_by_name['pull'].message_type = _IMAGEPULL
_IMAGEPULLSUMMARY.fields_by_name['start_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_IMAGEPULLSUMMARY.fields_by_name['end_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_IMAGEPULLSUMMARY.fields_by_name['layers'].message_type = _LAYERSTAT
DESCRIPTOR.message_types_by_name['ImagePull'] = _IMAGEPULL
DESCRIPTOR.message_types_by_name['LayerStat'] = _LAYERSTAT
DESCRIPTOR.message_types_by_name['ImagePullSummary'] = _IMAGEPULLSUMMARY
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImagePull = _reflection.GeneratedProtocolMessageType('ImagePull', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEPULL,
  __module__ = 'puller_pb2'
  # @@protoc_insertion_point(class_scope:dejavu.puller.ImagePull)
  ))
_sym_db.RegisterMessage(ImagePull)

LayerStat = _reflection.GeneratedProtocolMessageType('LayerStat', (_message.Message,), dict(
  DESCRIPTOR = _LAYERSTAT,
  __module__ = 'puller_pb2'
  # @@protoc_insertion_point(class_scope:dejavu.puller.LayerStat)
  ))
_sym_db.RegisterMessage(LayerStat)

ImagePullSummary = _reflection.GeneratedProtocolMessageType('ImagePullSummary', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEPULLSUMMARY,
  __module__ = 'puller_pb2'
  # @@protoc_insertion_point(class_scope:dejavu.puller.ImagePullSummary)
  ))
_sym_db.RegisterMessage(ImagePullSummary)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), dict(
  DESCRIPTOR = _CONFIG,
  __module__ = 'puller_pb2'
  # @@protoc_insertion_point(class_scope:dejavu.puller.Config)
  ))
_sym_db.RegisterMessage(Config)



_IMAGEPULLER = _descriptor.ServiceDescriptor(
  name='ImagePuller',
  full_name='dejavu.puller.ImagePuller',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=742,
  serialized_end=949,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetConfig',
    full_name='dejavu.puller.ImagePuller.SetConfig',
    index=0,
    containing_service=None,
    input_type=_CONFIG,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Pull',
    full_name='dejavu.puller.ImagePuller.Pull',
    index=1,
    containing_service=None,
    input_type=_IMAGEPULL,
    output_type=_IMAGEPULLSUMMARY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Prune',
    full_name='dejavu.puller.ImagePuller.Prune',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGEPULLER)

DESCRIPTOR.services_by_name['ImagePuller'] = _IMAGEPULLER

# @@protoc_insertion_point(module_scope)
