# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: puller.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='puller.proto',
  package='dejavu.puller',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cpuller.proto\x12\rdejavu.puller\x1a\x1fgoogle/protobuf/timestamp.proto\"6\n\tImagePull\x12\x0c\n\x04repo\x18\x01 \x01(\t\x12\x0b\n\x03tag\x18\x02 \x01(\t\x12\x0e\n\x06\x63lient\x18\x03 \x01(\t\"N\n\x11ImagePullSequence\x12\'\n\x05pulls\x18\x01 \x03(\x0b\x32\x18.dejavu.puller.ImagePull\x12\x10\n\x08registry\x18\x02 \x01(\t\"\x98\x01\n\x10ImagePullSummary\x12&\n\x04pull\x18\x01 \x01(\x0b\x32\x18.dejavu.puller.ImagePull\x12.\n\nstart_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\\\n\x0bImagePuller\x12M\n\x04Pull\x12 .dejavu.puller.ImagePullSequence\x1a\x1f.dejavu.puller.ImagePullSummary\"\x00\x30\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_IMAGEPULL = _descriptor.Descriptor(
  name='ImagePull',
  full_name='dejavu.puller.ImagePull',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='repo', full_name='dejavu.puller.ImagePull.repo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='dejavu.puller.ImagePull.tag', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client', full_name='dejavu.puller.ImagePull.client', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=118,
)


_IMAGEPULLSEQUENCE = _descriptor.Descriptor(
  name='ImagePullSequence',
  full_name='dejavu.puller.ImagePullSequence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pulls', full_name='dejavu.puller.ImagePullSequence.pulls', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='registry', full_name='dejavu.puller.ImagePullSequence.registry', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=198,
)


_IMAGEPULLSUMMARY = _descriptor.Descriptor(
  name='ImagePullSummary',
  full_name='dejavu.puller.ImagePullSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pull', full_name='dejavu.puller.ImagePullSummary.pull', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='dejavu.puller.ImagePullSummary.start_time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='dejavu.puller.ImagePullSummary.end_time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=353,
)

_IMAGEPULLSEQUENCE.fields_by_name['pulls'].message_type = _IMAGEPULL
_IMAGEPULLSUMMARY.fields_by_name['pull'].message_type = _IMAGEPULL
_IMAGEPULLSUMMARY.fields_by_name['start_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_IMAGEPULLSUMMARY.fields_by_name['end_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['ImagePull'] = _IMAGEPULL
DESCRIPTOR.message_types_by_name['ImagePullSequence'] = _IMAGEPULLSEQUENCE
DESCRIPTOR.message_types_by_name['ImagePullSummary'] = _IMAGEPULLSUMMARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImagePull = _reflection.GeneratedProtocolMessageType('ImagePull', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEPULL,
  __module__ = 'puller_pb2'
  # @@protoc_insertion_point(class_scope:dejavu.puller.ImagePull)
  ))
_sym_db.RegisterMessage(ImagePull)

ImagePullSequence = _reflection.GeneratedProtocolMessageType('ImagePullSequence', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEPULLSEQUENCE,
  __module__ = 'puller_pb2'
  # @@protoc_insertion_point(class_scope:dejavu.puller.ImagePullSequence)
  ))
_sym_db.RegisterMessage(ImagePullSequence)

ImagePullSummary = _reflection.GeneratedProtocolMessageType('ImagePullSummary', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEPULLSUMMARY,
  __module__ = 'puller_pb2'
  # @@protoc_insertion_point(class_scope:dejavu.puller.ImagePullSummary)
  ))
_sym_db.RegisterMessage(ImagePullSummary)



_IMAGEPULLER = _descriptor.ServiceDescriptor(
  name='ImagePuller',
  full_name='dejavu.puller.ImagePuller',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=355,
  serialized_end=447,
  methods=[
  _descriptor.MethodDescriptor(
    name='Pull',
    full_name='dejavu.puller.ImagePuller.Pull',
    index=0,
    containing_service=None,
    input_type=_IMAGEPULLSEQUENCE,
    output_type=_IMAGEPULLSUMMARY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGEPULLER)

DESCRIPTOR.services_by_name['ImagePuller'] = _IMAGEPULLER

# @@protoc_insertion_point(module_scope)
