# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import builder.builder_pb2 as builder__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ImageBuilderStub(object):
  """ImageBuilder builds and publish images as requested.
  It runs in front of a Docker registry where the images are published
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Build = channel.unary_unary(
        '/dejavu.builder.ImageBuilder/Build',
        request_serializer=builder__pb2.ImageBuildSet.SerializeToString,
        response_deserializer=builder__pb2.BuilderResponse.FromString,
        )
    self.Purge = channel.unary_unary(
        '/dejavu.builder.ImageBuilder/Purge',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=builder__pb2.BuilderResponse.FromString,
        )


class ImageBuilderServicer(object):
  """ImageBuilder builds and publish images as requested.
  It runs in front of a Docker registry where the images are published
  """

  def Build(self, request, context):
    """Build builds and publishes images specified in the ImageBuildSet.
    It returns 200 if images are built successfully but error code otherwise 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Purge(self, request, context):
    """Purge purges both the manifests and blobs in the registry behind. 
    It returns 200 if the registry has been successfully purged but error code otherwise
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ImageBuilderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Build': grpc.unary_unary_rpc_method_handler(
          servicer.Build,
          request_deserializer=builder__pb2.ImageBuildSet.FromString,
          response_serializer=builder__pb2.BuilderResponse.SerializeToString,
      ),
      'Purge': grpc.unary_unary_rpc_method_handler(
          servicer.Purge,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=builder__pb2.BuilderResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dejavu.builder.ImageBuilder', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
